### ISSUE TITLE
Cloudflare Rate Limiting Too Aggressive

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#964]
I can't load the staking UI (start from uad.ubq.fi, navigate to staking) due to rate limits. We need some exceptions on this subdomain.

**Comment by 0x4007** [comment]
@rndquu how was rate limiting set up? I can't seem to find it on Cloudflare

**Comment by rndquu** [comment]
> @rndquu how was rate limiting set up? I can't seem to find it on Cloudflare

1. Rate limiting for `uad.ubq.fi` was set up [this](https://developers.cloudflare.com/waf/reference/legacy/old-rate-limiting/#create-a-custom-rate-limiting-rule) way. Try to search for rate limiting rules in cloudflare dashboard:
  a) `Security > WAF > Rate limiting rules`
  b) In the "Rules" section of the `ubq.fi` domain settings
  
<img width="1512" alt="Screenshot 2024-09-27 at 17 47 30" src="https://github.com/user-attachments/assets/f3e6f320-1306-4a7a-b384-c1ce807f2d59">

I don't have permissions to view the rules in the cloudflare dashboard for your account.

2. I've also accidentally found the redirect rule for the `ethcon.ubq.fi` subdomain. Perhaps try to move it higher in the UI so that it takes precedence over the `*.ubq.fi/*` rule.

<img width="1512" alt="Screenshot 2024-09-27 at 17 50 52" src="https://github.com/user-attachments/assets/6c13faef-bfdc-4e0f-acc4-20ee10eff52b">

**Comment by 0x4007** [comment]
Fixed 1. but 2. it looks like `*.ubq.fi/*` is not enabled so I don't think this is the full picture.

**Comment by 0x4007** [comment]
@gentlementlegen can you fix the main branch of conversation rewards

**Comment by gentlementlegen** [comment]
@0x4007 Then I will merge https://github.com/ubiquity-os-marketplace/text-conversation-rewards/pull/142 and still work on the fixes that will be merged afterwards.

**Comment by 0x4007** [comment]
Looks like the settings of behavior is wrong. rndquu should have received some credit for the comment

**Comment by gentlementlegen** [comment]
The `p` are still excluded from word count, I didn't fix it yet. You can temporarily fix it by setting explicitly all the values in the configuration.
